# File: .github/workflows/alembic-diff-check.yml | Version: 1.1 | Path: /.github/workflows/alembic-diff-check.yml
name: Alembic Diff Check

on:
  push:
    branches: [ main, housekeeping-phase5 ]
  pull_request:
    branches: [ main ]

jobs:
  alembic-diff:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
      DATABASE_URL: sqlite:///./_ci_alembic.db

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install alembic SQLAlchemy aiosqlite
          test -f requirements.txt && pip install -r requirements.txt || true
          test -f requirements-dev.txt && pip install -r requirements-dev.txt || true

      - name: Sanity & environment
        run: |
          python - <<'PY'
          import os, sys
          sys.path.insert(0, os.getcwd())
          import app
          print("✅ app import OK")
          print("PYTHONPATH=", os.environ.get("PYTHONPATH"))
          print("DATABASE_URL=", os.environ.get("DATABASE_URL"))
          PY
          alembic --version
          rm -f _ci_alembic.db || true
          ls -la

      - name: Migrate (fresh DB)
        run: |
          set -euxo pipefail
          alembic heads
          alembic current || true
          alembic upgrade head
          alembic current
