name: Alembic Diff Check
on:
  push:
    branches: [ main, housekeeping-phase5 ]
  pull_request:
    branches: [ main ]

jobs:
  alembic-diff:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: sqlite:///./test.db
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Upgrade DB
        run: alembic upgrade head
      - name: Count migrations before
        id: before
        run: echo "count_before=$(ls -1 alembic/versions | wc -l)" >> $GITHUB_OUTPUT
      - name: Autogenerate (dry check)
        run: alembic revision --autogenerate -m "ci-autogen-check" || true
      - name: Count migrations after
        id: after
        run: echo "count_after=$(ls -1 alembic/versions | wc -l)" >> $GITHUB_OUTPUT
      - name: Fail if drift detected
        if: ${{ steps.after.outputs.count_after != steps.before.outputs.count_before }}
        run: |
          echo "::error::Schema drift detected. Commit an Alembic revision."
          exit 1
      - name: Cleanup any generated file
        if: ${{ steps.after.outputs.count_after != steps.before.outputs.count_before }}
        run: rm -f alembic/versions/*.py
