name: CI / tests
on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]   # single version to match one check
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - run: python -m pip install --upgrade pip setuptools wheel
      - run: pip install -r requirements-dev.txt || pip install -r requirements.txt
      - run: pytest -q
