name: CI / tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Upgrade pip tooling
        run: python -m pip install --upgrade pip setuptools wheel

      # Install deps (handles either requirements-dev.txt or requirements.txt;
      # if neither exists, installs a minimal set that matches this repo)
      - name: Install dependencies
        shell: bash
        run: |
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install \
              "fastapi>=0.110" "uvicorn[standard]>=0.23" \
              "pydantic>=2,<3" "sqlalchemy>=2.0.0" \
              "python-jose[cryptography]>=3.3" "passlib[bcrypt]>=1.7" \
              "python-multipart>=0.0.6" "email-validator>=2.0" \
              "pytest>=7" "httpx>=0.24"
          fi

      - name: Run tests
        env:
          PYTHONPATH: .
        run: pytest -q
